name: TissueBox
description: A mobile phone game made by Flutter.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flame: "0.10.2"
  shared_preferences: ^0.5.1+2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/crown
    - assets/images/bg1
    - assets/images/tb0
    - assets/images/tb1
    - assets/images/tb2
    - assets/images/ts1
    - assets/audio/ts1
    - assets/audio/ts2
    - assets/audio/ts3
    - assets/audio/tk
    - assets/audio/ba
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700